# Generated by Django 6.0.6 on 2026-06-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="author",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="category",
            name="comments",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="date",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to="blog/category/"),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
