# Generated by Django 6.0.6 on 2026-06-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_author_category_comments_category_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
