# Generated by Django 6.0.6 on 2026-06-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="author",
        ),
        migrations.RemoveField(
            model_name="category",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="category",
            name="date",
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="views",
        ),
    ]
