# Generated by Django 6.0.6 on 2026-06-22 18:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_author_image"),
        ("blog", "0004_remove_category_author_remove_category_comments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="blog/%Y/%m")),
                ("date", models.DateField(blank=True, default=datetime.date.today)),
                ("views", models.PositiveIntegerField(blank=True, default=0)),
                ("comments", models.PositiveIntegerField(blank=True, default=0)),
                ("full_text", models.TextField(blank=True)),
                ("abstract", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=200)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="author.author"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Posts",
            },
        ),
    ]
