# Generated by Django 6.0.6 on 2026-06-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
