# Generated by Django 6.0.6 on 2026-06-23 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date",
            new_name="published_date",
        ),
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="send_date",
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
