# Generated by Django 6.0.6 on 2026-06-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("biography", models.TextField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("pinterest", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
