# Generated by Django 6.0.6 on 2026-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
