# Generated by Django 6.0.6 on 2026-06-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_title", models.CharField(blank=True, max_length=50)),
                ("website_title", models.CharField(blank=True, max_length=50)),
                ("favicon", models.ImageField(blank=True, upload_to="main")),
                ("light_logo", models.ImageField(blank=True, upload_to="main")),
                ("dark_logo", models.ImageField(blank=True, upload_to="main")),
            ],
            options={
                "verbose_name": "Main Details",
                "verbose_name_plural": "Main Details",
            },
        ),
    ]
