# Generated by Django 6.0.6 on 2026-06-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mymodel",
            name="copyright",
            field=models.TextField(blank=True),
        ),
    ]
