# Generated by Django 6.0.6 on 2026-06-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_mymodel_copyright"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mymodel",
            old_name="dark_logo",
            new_name="logo",
        ),
        migrations.RemoveField(
            model_name="mymodel",
            name="light_logo",
        ),
    ]
