# Generated by Django 6.0.6 on 2026-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_dark_logo_mymodel_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.CharField(blank=True, max_length=30)),
                ("icon", models.CharField(blank=True, max_length=30)),
                ("link", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "verbose_name": "Social",
                "verbose_name_plural": "Socials",
            },
        ),
    ]
