# Generated by Django 6.0.6 on 2026-06-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="social",
            name="link",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
