# Generated by Django 6.0.6 on 2026-06-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_social_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="social",
            name="link",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
