# Generated by Django 6.0.6 on 2026-06-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_social_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="position",
            field=models.PositiveSmallIntegerField(blank=True, default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="social",
            name="website_title",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="social",
            name="link",
            field=models.TextField(blank=True),
        ),
    ]
